//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blackbox.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about back-box.
        /// </summary>
        public static string AboutApplicationBarMenuItemText {
            get {
                return ResourceManager.GetString("AboutApplicationBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed by Panda Games Studio
        ///Designer: Sun Jinbo
        ///Email: sunjinbo@hotmail.com.
        /// </summary>
        public static string AboutAuthorText {
            get {
                return ResourceManager.GetString("AboutAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black-box™ for Windows Phone 7
        ///Version 01.00.00
        ///Copyright © 2011-2012 by Panda Games Studio
        ///All rights reserved..
        /// </summary>
        public static string AboutContentText {
            get {
                return ResourceManager.GetString("AboutContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black-box (TM) for Windows Phone 7 designed and written by Panda Game Studio..
        /// </summary>
        public static string AboutHelpDetailsText {
            get {
                return ResourceManager.GetString("AboutHelpDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutHelpTitleText {
            get {
                return ResourceManager.GetString("AboutHelpTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All at once.
        /// </summary>
        public static string AllAtOnceText {
            get {
                return ResourceManager.GetString("AllAtOnceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All at a time.
        /// </summary>
        public static string AllAtTimeText {
            get {
                return ResourceManager.GetString("AllAtTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLACK-BOX.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black-box™.
        /// </summary>
        public static string AppNameHubTileNotification {
            get {
                return ResourceManager.GetString("AppNameHubTileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AppNameHubTileTitle {
            get {
                return ResourceManager.GetString("AppNameHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunjinbo@hotmail.com.
        /// </summary>
        public static string AuthorHubTileNotification {
            get {
                return ResourceManager.GetString("AuthorHubTileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorHubTileTitle {
            get {
                return ResourceManager.GetString("AuthorHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tieto China Co., Ltd..
        /// </summary>
        public static string CorporationHubTileNotification {
            get {
                return ResourceManager.GetString("CorporationHubTileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CorporationHubTileTitle {
            get {
                return ResourceManager.GetString("CorporationHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debunk.
        /// </summary>
        public static string DebunkApplicationBarText {
            get {
                return ResourceManager.GetString("DebunkApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rays that goes one cell to the left or to the right of a ball will be deflected by 90 degrees out of the ball..
        /// </summary>
        public static string DeflectionHelpItemDetailsText {
            get {
                return ResourceManager.GetString("DeflectionHelpItemDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deflection.
        /// </summary>
        public static string DeflectionHelpItemTitleText {
            get {
                return ResourceManager.GetString("DeflectionHelpItemTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string GamePageTitle {
            get {
                return ResourceManager.GetString("GamePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Success belongs to the persevering.&quot;.
        /// </summary>
        public static string GameStudioHubTileNotification {
            get {
                return ResourceManager.GetString("GameStudioHubTileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panda Games Studio.
        /// </summary>
        public static string GameStudioHubTileTitle {
            get {
                return ResourceManager.GetString("GameStudioHubTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guess.
        /// </summary>
        public static string GuessApplicationBarText {
            get {
                return ResourceManager.GetString("GuessApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess type.
        /// </summary>
        public static string GuessTypeTitle {
            get {
                return ResourceManager.GetString("GuessTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help contents.
        /// </summary>
        public static string HelpApplicationBarMenuItemText {
            get {
                return ResourceManager.GetString("HelpApplicationBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpApplicationBarText {
            get {
                return ResourceManager.GetString("HelpApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rays that hits a ball will be absorbed (it will not come outside the box)..
        /// </summary>
        public static string HitHelpItemDetailsText {
            get {
                return ResourceManager.GetString("HitHelpItemDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        public static string HitHelpItemTitleText {
            get {
                return ResourceManager.GetString("HitHelpItemTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black-box™ is a game of &quot;hide and seek&quot;, which simulates shooting rays into a black box to deduce the locations of atoms hidden inside. It was created by Eric Solomon in 1970s. Currently it has numerous computer implementations for many different platforms, perhaps this one is the first on Windows Phone platform,  hope you like it..
        /// </summary>
        public static string IntroductionHelpDetailsText {
            get {
                return ResourceManager.GetString("IntroductionHelpDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string IntroductionHelpTitleText {
            get {
                return ResourceManager.GetString("IntroductionHelpTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of mirrors.
        /// </summary>
        public static string MirrorNumberTitle {
            get {
                return ResourceManager.GetString("MirrorNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ray that doesn&apos;t come across with any ball with go straight through the box..
        /// </summary>
        public static string MissHelpItemDetailsText {
            get {
                return ResourceManager.GetString("MissHelpItemDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        public static string MissHelpItemTitleText {
            get {
                return ResourceManager.GetString("MissHelpItemTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string NextApplicationBarText {
            get {
                return ResourceManager.GetString("NextApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OkApplicationBarText {
            get {
                return ResourceManager.GetString("OkApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string PreviousApplicationBarText {
            get {
                return ResourceManager.GetString("PreviousApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want a rematch.
        /// </summary>
        public static string RestartApplicationBarMenuItemText {
            get {
                return ResourceManager.GetString("RestartApplicationBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        public static string RestartApplicationBarText {
            get {
                return ResourceManager.GetString("RestartApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions of these ray behavior rules can be found by clicking on the User&apos;s Guide link below, or from a similar link on the game board during play..
        /// </summary>
        public static string RulesHelpSynopsisText {
            get {
                return ResourceManager.GetString("RulesHelpSynopsisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string RulesHelpTitleText {
            get {
                return ResourceManager.GetString("RulesHelpTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsApplicationBarText {
            get {
                return ResourceManager.GetString("SettingsApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipApplicationBarText {
            get {
                return ResourceManager.GetString("SkipApplicationBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string SoundTitle {
            get {
                return ResourceManager.GetString("SoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started!.
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the game, 3 to 5 balls (depending on how many you choose when starting the game) are hidden in an 8-by-8 grid. You supply inputs in the form of &quot;rays&quot; that you &quot;shoot&quot; into the sides of the grid. Because these rays behave according to deterministic rules when in the vicinity of a ball within the grid, you can deduce the locations of the balls given their observed behavior. The object of the game is to accurately guess the location of the hidden balls using the least amount of information..
        /// </summary>
        public static string TargetHelpDetailsText {
            get {
                return ResourceManager.GetString("TargetHelpDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object of the game.
        /// </summary>
        public static string TargetHelpTitleText {
            get {
                return ResourceManager.GetString("TargetHelpTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow unlimited rays.
        /// </summary>
        public static string UnlimitedRaysTitle {
            get {
                return ResourceManager.GetString("UnlimitedRaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        public static string VibrateTitle {
            get {
                return ResourceManager.GetString("VibrateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of the game is to use deductive reasoning to determine the location of 3 to 5 &apos;mirrors&apos; placed unseen within an 8-by-8 grid. For more information, please refer to the Help..
        /// </summary>
        public static string WelcomeAddressText {
            get {
                return ResourceManager.GetString("WelcomeAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
    }
}
